language: python
python:
  - "2.7"
  - "3.4"
# command to install dependencies
install:
  - "pip install -r requirements.txt"

script:
  - python iceleracli.py -f example/example.dat
  - diff example/example.dat.csv example/example.dat.csv.base
